bnb-chain/bsc-genesis-contract

test/BSCValidatorSet.js
The initial number of up limit validators is setting to 21, give the worst case, we may increase it to 41 validators. Currently the logic of updating validators is quite complicated, we would like to perform the gas analyses for this worst-case execution scenarios.
The test reset shows that it will consume 2626836 gas for 41 valdiators, far away from the  40000000 block gas limit.
=> [R4R]perform the gas analyses for worst-case executions scenarios (41 validators)

contracts/SlashIndicator.sol, contracts/SlashIndicator.template, test/GovHub.js
when threshold parameters change, under certain circumstances, slash func would be allowed to
trigger felonies without a prior misdemeanour.
=> [R4R]fix potentially unintentional felony without a prior misdemeanour

wbnb/WBNB.sol
=> R4R: implement WBNB

contracts/Staking.sol, contracts/Staking.template, contracts/TokenHub.sol, contracts/TokenHub.template, contracts/mock/MockTokenHub.sol
Add more balance and address check to make the module more robust.
N/A
N/A
- Use `call` instead of `transfer` to send BNB
- Add more balance check
=> update: fix some audit issues

contracts/CrossChain.sol, contracts/CrossChain.template
This PR added a check to save gas.
To save gas.
N/A
- Add height check.
=> update: add height check to save gas

contracts/RelayerHub.sol, test/RelayerHub.t.sol
Remove dues (along with the 100BNB requirement which was removed before).
=> Relayer admin Remove Dues

test/RelayerHub.t.sol
Since adding a new manager is a repeated action in the RelayerHub tests, I am extracting it into a helper function `addNewManager` . This avoids some code duplication.
=> Extract helper function for RelayerHub tests

genesis-template.json, genesis.json
This PR aims to add new hardforks' block height to genesis-template.json for test convenience.
- Add gibbs block
- Add moran block
=> upgrade: add new hardforks' block height to genesis-template.json

genesis-template.json, genesis.json
This PR aims to rename the hardfork name, boneh and lynn will not be used any longer, will be replaced with luban and plato.
No impact to users.
=> rename: to luban & plato

contracts/BSCValidatorSet.sol, contracts/BSCValidatorSet.template, contracts/SlashIndicator.sol, contracts/SlashIndicator.template, contracts/interface/IBSCValidatorSet.sol
Description
merge develop into master for release
Rationale
Example
Changes
add each change in a bullet point here
...
=>  fix: not limit source number into (block.number-256,) for slashing malicious vote (#293)

abi/bscvalidatorset.abi, abi/relayerhub.abi, abi/slashindicator.abi, abi/tendermintlightclient.abi
=> Update contracts' abi

contracts/BC_fusion/BSCGovernor.sol
update quorumNumerator param typo
=> fix: update quorumNumerator param typo

contracts/SlashIndicator.sol
Description
give enough time to handle malicious vote slash
Rationale
even we can limit source block and target block in recent 256 blocks, 
they may on other fork instead of the main fork, so we still can't check the validity of block Hash.
otherwise, 256 blocks is too hasty for handling malicious slash, we need change `256` to a reasonable value.
3 days as init, can be changed by govern, range from 1 days to 30 days.
Example
Changes
add each change in a bullet point here
...
=> fix: give enough time to handle malicious vote slash

contracts/SlashIndicator.sol, contracts/System.sol
This pr is to fix build errors
* move `onlyZeroGasPrice` to `System`
=> fix: move `onlyZeroGasPrice` to `System`

contracts/BSCValidatorSet.sol
pls refer https://github.com/bnb-chain/BEPs/pull/319
=> Make fast finality rewards governable

contracts/BSCValidatorSet.sol
refer to https://github.com/bnb-chain/BEPs/pull/328/files
=> keep burn ratio in BEP-95

contracts/BC_fusion/BSCGovernor.sol, contracts/BC_fusion/BSCTimelock.sol, contracts/BC_fusion/GovToken.sol
1. add pause method for BSCGovernor
2. add comments for BSCGovernor and GovToken
=> feat: add comments and pause for governor

abi/bscvalidatorset.abi, abi/stakehub.abi, contracts/BC_fusion/StakeHub.sol, test/StakeHub.t.sol, test/utils/interface/IBSCValidatorSet.sol, test/utils/interface/IStakeHub.sol
This pr is mainly to add a new view function to pagination query all validators' operator address and credit contract address
* add view function `getValidators`
* add `Delegated` event when creating validator
=> chore: add view function and update annotations

abi/stakecredit.abi, abi/stakehub.abi, contracts/BC_fusion/StakeCredit.sol, contracts/BC_fusion/StakeHub.sol, test/StakeHub.t.sol, test/utils/interface/IStakeCredit.sol, test/utils/interface/IStakeHub.sol
This pr is to fix some issues from audit report
* add check that the returned shares of delegation cannot be zero
* add event of stake credit contract initialized
* remove unused code
=> chore: fix issues from audit report

contracts/BC_fusion/StakeHub.sol
This pr is to fix an issue within `StakeHub`
* fix wrong jail time in `_checkValidatorSelfDelegation`
=> fix: wrong jail time in `_checkValidatorSelfDelegation`

contracts/BC_fusion/StakeHub.sol
This pr is to add code annotation to make it more easy to understand 
* add code annotation
=> chore: add annotation

abi/tokenhub.abi
=> docs: update tokenhub abi

contracts/BC_fusion/BSCGovernor.sol, contracts/BC_fusion/StakeHub.sol
This pr is to add upper limit for some params 
To prevent unreasonable settings
* add upper limit for some params
=> fix: add upper limit for some params

abi/bscgovernor.abi, abi/stakehub.abi, abi/tendermintlightclient.abi, abi/tokenmanager.abi, contracts/BC_fusion/BSCGovernor.sol, contracts/BC_fusion/StakeCredit.sol, contracts/BC_fusion/StakeHub.sol, contracts/BC_fusion/TokenRecoverPortal.sol
This pr is to fix some issues from the audit report
* add `__ReentrancyGuard_init_unchained` to StakeCredit and TokenRecoverPortal contracts
* add `removeTmpMigratedValidator` to 3 slash functions
* add events for blacklist
=> chore: fix audit issues

contracts/BC_fusion/StakeHub.sol, test/Governor.t.sol, test/SlashIndicator.t.sol, test/utils/interface/IStakeHub.sol
add unit test for governor test
* add governor test file and rebase for bc-fusion
=> feat: add governor test

abi/tokenrecoverportal.abi
update token recover portal abi
=> docs: update token recover portal abi

contracts/BSCValidatorSet.sol, test/Governor.t.sol
This pr is to fix the issue that all the validators may be jailed in `_forceMaintainingValidatorsExit`
=> fix: add check to make sure there is at least one validator in `_forceMaintainingValidatorsExit`

abi/tokenrecoverportal.abi
This pr is to update the tokenRecoverPortal's abi file
=> chore: update tokenrecoverportal.abi

test/StakeHub.t.sol
add a description of your changes here...
* ...
=> chore: add unit test

contracts/BC_fusion/StakeHub.sol
This pr is to update the redelegate fee rate base to 100000
* update redelegate fee rate base to 100000
=> chore: update redelegate fee rate base to 100000

scripts/generate.py, test/TokenHub.t.sol, test/utils/Deployer.sol
This pr is to fix some typo in the `generate.py` and some unit test issues
* fix typo
* fix unit tests
=> chore: fix typo and unit tests

abi/slashindicator.abi, contracts/BSCValidatorSet.sol, contracts/SlashIndicator.sol, contracts/interface/ISlashIndicator.sol, poetry.lock, test/SlashIndicator.t.sol, test/utils/Deployer.sol, test/utils/RLPDecode.sol, test/utils/RLPEncode.sol, test/utils/interface/ISlashIndicator.sol
This pr is to merge master branch into develop
* fix: array out-of-bounds issue in _exitMaintenance (#565)
=> chore: merge master branch into develop

contracts/BC_fusion/StakeHub.sol
add paused check and blacklist check for updateAgent
* add paused check and blacklist check for updateAgent
* ...
=> fix: add paused check and blacklist check for updateAgent

contracts/BC_fusion/lib/RLPDecode.sol, contracts/lib/RLPDecode.sol, test/utils/RLPDecode.sol
=> chore: fix some comments

contracts/BC_fusion/StakeHub.sol
add a description of your changes here...
* ...
=> fix: not set agentToOperator while newAgent is zero address (#579)

scripts/init_holders.template
fix: update init_holders.template
* ...
=> fix: update init_holders.template

scripts/init_holders.template
fix: update init_holders.template (#594)
* ...
=> fix: update init_holders.template (#594)

contracts/BSCGovernor.sol, contracts/BSCValidatorSet.sol
chore: update some comments
no bytecode changes
* ...
=> chore: update some comments

README.md
chore: simplify introduction for running 'forge test'
* ...
=> chore: simplify introduction for running 'forge test'

.github/workflows/check-genesis.yml, .github/workflows/unit-test.yml, test/Governor.t.sol, test/SlashIndicator.t.sol, test/ValidatorSet.t.sol
chore: fix unit-test CI
1. new version forge has no flag `--no--commit`
2. lorentz hardfork passed on mainnet, some cases failed, 
all fixed in this PR
* ...
=> chore: fix unit-test CI
