contracts/SlashIndicator.sol, contracts/SlashIndicator.template
In SlashIndicator.sol, L66 and L76, handleAckPackage(...) and handleFailAckPackage(...) are missing access control and are callable by anyone in the public. This would cause events knownResponse(...), unKnownResponse(...), and crashResponse(...) to be emitted unintentionally. The methods also miss the onlyInit modifier.
=> [R4R]fix Missing access control of slash contract

contracts/BSCValidatorSet.sol, contracts/BSCValidatorSet.template, test/BSCValidatorSet.js
Currently, the number of BSC validators is not limited in the contracts.  The max intended number of BSC validators is 41.
=> [R4R] Validator count to be enforced in the smart contracts

contracts/SlashIndicator.sol, contracts/SlashIndicator.template, test/Slash.js
Even if the validator update happens once per day, a validator can still harm just before the update happens, and then leave. The incentives exists: there are many people out there who will be satisfied just with the fact that they were able to misbehave and not get punished.
To prevent validator misbehaving and leaving, do not clean slash record to zero, but decrease by felonyThreshold/DECREASE_RATE , this can not totally prevent it but can relieve it.
=> [R4R]prevent validator misbehaving and leaving

contracts/bep20_template/BEP20Token.template, contracts/interface/IBEP20.sol, contracts/test/ABCToken.sol, contracts/test/DEFToken.sol, contracts/test/MaliciousToken.sol, contracts/test/MiniToken.sol
Update decimals return type to uint8 in BEP20 interface
=> R4R: update decimals return type to uint8

abi/staking.abi, contracts/Staking.sol, contracts/Staking.template, contracts/interface/IStaking.sol
There may be some vulnerability in previous native staking design. 
N/A
For example, if a user sends the `delegate` transaction with invalid validator, execute the `undelegate` transaction immediately before receiving the AckPackage of the last delegate transaction, the token from the last delegate transaction will be locked.
For now, every request from BSC to BC will have an ack package to inform the status of the request. State changes will be done only after the ack package with success status is received.
=> fix: update cross chain logic of native stake

contracts/CrossChain.sol, contracts/CrossChain.template
This PR tries to increase the cost of cross-chain vulnerability exploitation.
The hacker registered as a `relayer` and exploit the merkle proof vulnerability,  the BC block header that he use is an ancient block which obviously does not have the latest packages,  this PR will introduce the header check to prevent such situation
NA
- Add `channelSyncedHeaderMap` to record the most recent synced header's height. New packages' height cannot be smaller than the recorded height.
=> fix: add height check for cross chain package

contracts/CrossChain.sol, contracts/CrossChain.template
This PR fix a stack too deep error in crossChain contract.
N/A
N/A
- Split `handlePackage` into two parts.
=> fix: stack too deep error

contracts/CrossChain.sol, contracts/CrossChain.template
This is a fix that update gov param for BEP-171
in the previous code, `BytesToTypes.bytesToUint16(32, value)` for uint16 will not be correctly set while input a bytes2 param.   
set `BytesToTypes.bytesToUint16(2, value)` for uint16 params
* set `BytesToTypes.bytesToUint16(2, value)` for uint16 params
=> fix(BEP-171): modify params length to 2 for uint16

README.md
In this pr, the readme guide user to generate the genesis file in one short command.
Currently, when we upgrade a smart contract on BSC network, it is hard for another developer to verify whether the byte code is right or not.
We introduce some docs in this PR, so that reviewer can easily verify the bytecode.
NA
Nono
=> docs: add how to generate mainnet/testnet/QA genesis file

contracts/BSCValidatorSet.sol, contracts/BSCValidatorSet.template, contracts/SlashIndicator.sol, contracts/SlashIndicator.template, contracts/Staking.sol, contracts/Staking.template, contracts/TokenHub.sol, contracts/TokenHub.template
Add more comments for TokenHub contract.
=> docs: add more comments for contracts

contracts/RelayerHub.sol, lib/interface/IRelayerHub.sol, test/RelayerHub.t.sol
There was a bug where if a 2 managers register their relayers and 1 of them sets it to 0 and then the other one tries to set it to 0 then it won't work.
The setting to address(0) part needed special handling, so the require check is not required for this. 
This PR adds a test(`testRelayerAddingRemoving2()`) which captures that bug and then it is fixed.
=> Relayer admin bugfix

contracts/BSCValidatorSet.sol, contracts/BSCValidatorSet.template, test/ValidatorSet.t.sol
This PR is to fix errors within `BSCValidatorSet` contract
* add more comments
* fix error within doUpdateState function
* fix typo
=> fix: error in BSCValidatorSet

contracts/BSCValidatorSet.sol, contracts/BSCValidatorSet.template, contracts/SlashIndicator.sol, contracts/SlashIndicator.template
Description
malicious vote affects the safety of bsc seriously, 
so we need slash more BNBs for malicious vote and no matter whether slashed validator is active.
Rationale
1. after a validator generating a malicious vote, it can go down on purpose to avoid to be slashed.
so we change the mechanism to slash it no matter whether it's active.
2. slash amount is 50 BNBs, more need to be slashed.
so we send a different crosschain pack and handle it in bc node correspondingly 
Example
tested in new qa
N/A
=> fix: slash more bnbs for malicious vote and no matter whether slashed validator is active.

genesis-template.json
This PR is quite simple:
as we enable `planck` upgrade on both testnet and mainnet, we can enable it on local network by default.
=> fork: enable planckBlock by default

genesis-template.json, genesis.json
This PR aims to rename the hardfork name, boneh and lynn will not be used any longer, will be replaced with luban and plato.
No impact to users.
=> rename: rename hardfork name to luban & plato

contracts/BSCValidatorSet.sol, contracts/BSCValidatorSet.template
This PR aims to fix the wrong refund address assignment in `updateValidatorSet` function.
No impact to users.
=> fxi: wrong refund address in `updateValidatorSet`

contracts/BSCValidatorSet.sol, contracts/BSCValidatorSet.template
This PR aims to fix the wrong refund address assignment in `updateValidatorSet` function.
No impact to users.
=> fix: wrong refund address in `updateValidatorSet` (#286)

contracts/BSCValidatorSet.sol, contracts/BSCValidatorSet.template, contracts/SlashIndicator.sol, contracts/SlashIndicator.template, contracts/interface/IBSCValidatorSet.sol
For now, validator can be slashed for malicious vote signed by verify old vote keys.
this PR limit that vote keys should be in last two validator set which come from breathe block.
* ...
=> fix: protect validator from being slashed for malicious vote signed before

contracts/SlashIndicator.sol, contracts/SlashIndicator.template
Description
not limit source number into (block.number-256,) for slashing malicious vote
Rationale
one case:
because of some reason (like p2p propagation), attestation is not assembled for a period,  so justified block is a lot 
behind from _block.number_.  Then validators can use the justified block as sourceNumber to vote for  different blocks 
even they are at the same height.  It can harm network, but not slashed now.
so change _srcNum+256 > block.number_ --> _tarNum+256 > block.number_
Example
Changes
add each change in a bullet point here
...
=>    fix: not limit source number into (block.number-256,) for slashing malicious vote

contracts/BSCValidatorSet.sol
This pr is to change `MAX_NUM_OF_VALIDATORS` and add missing modifier in `BSCValidatorSet` contract
* change `MAX_NUM_OF_VALIDATORS` from 41 to 100
* add missing modifier `onlyZeroGasPrice` to some system functions
=> chore: change `MAX_NUM_OF_VALIDATORS` and add missing modifier

contracts/BSCValidatorSet.sol
simplify and stabilize rewards for fast finality
according to current logic of fast finality rewards
the prize is not stable, like a sequene [0.3BNB, 031BNB,0.42BNB, **1.01BNB**, 0.3BNB, 0.25BNB, 0.35BNB,0.2BNB,**1BNB**......]
every element in above array is the total reward for fast finality in a epoch.
this PR is to fix this issue.
add each change in a bullet point here
...
=> simplify and stabilize rewards for fast finality

contracts/BSCValidatorSet.sol, contracts/SlashIndicator.sol, contracts/SystemReward.sol, contracts/TokenHub.sol, contracts/interface/ISystemReward.sol
system rewards is limited within 1BNB even if we improve the ratio to much higner for fast finality rewards, 
so in this PR, we improve the system rewards for fast finality seperately.
if fast finality rewards ratio is 25%, the limit `5BNB`has not been touched is the past year https://bscscan.com/chart/blocks
=> improve rewards limit for fast finality

genesis-template.json, scripts/generate-tendermintLightClient.sh, scripts/generate.sh
1. unlike other system contracts, SystemReward has no function `init` , instead only have a modifier `doInit`,
to deploy local test easily, we need to init SystemReward, `claimRewards` called once to do it
2. add  `shanghaiTime` and `keplerTime` in genesis.json
set them to 0, meaning the same block with london hardfork
3. remove `fusionBlock` just for now, because related code is not merged,
will run into wrong when work with other scripts.
=> init SystemReward for local test and add shanghaiTime,keplerTime

contracts/BC_fusion/BSCGovernor.sol, contracts/BC_fusion/BSCTimelock.sol, contracts/GovHub.sol, contracts/System.sol
- these params is default in number of block not seconds
```    
uint256 private constant INIT_VOTING_DELAY = 24 hours / SECONDS_PER_BLOCK;
uint256 private constant INIT_VOTING_PERIOD = 14 days / SECONDS_PER_BLOCK;
uint64 private constant INIT_MIN_PERIOD_AFTER_QUORUM = uint64(1 days / SECONDS_PER_BLOCK);
```
- only allow `GovHub` in whitelist proposal targets, restrict permissions
- sync system contracts
=> fix: init params error in BSCGovernor

contracts/BC_fusion/StakeHub.sol, test/StakeHub.t.sol
This pr is to disable editing moniker in `StakeHub`
To ensure that moniker and token names remain consistent
* disable editing moniker in `StakeHub`
=> chore: disable editing moniker

abi/slashindicator.abi, abi/stakehub.abi, contracts/BC_fusion/StakeCredit.sol, contracts/BC_fusion/StakeHub.sol, contracts/BC_fusion/interface/IStakeHub.sol, contracts/BSCValidatorSet.sol, contracts/SlashIndicator.sol, contracts/interface/IStakeHub.sol, scripts/generate.py, test/SlashIndicator.t.sol, test/utils/interface/ISlashIndicator.sol, test/utils/interface/IStakeHub.sol
This pr is to update slash logic to avoid malicious slash
* add voteAddress/consensusAddress expiration
=> fix: update slash logic to avoid malicious slash

contracts/BSCValidatorSet.sol
This pr is to fix a bug that will leads to distribute reward twice
* Clear validator incoming after distribution at once
=> fix: ensure validator incoming will be clear after distribution

contracts/BC_fusion/TokenRecoverPortal.sol
1. fix code comment in TokenRecoverProtal.sol
=> fix: audit report

contracts/BC_fusion/BSCGovernor.sol
add whenNotPaused modifier for queue in BSCGovernor
=> feat: add whenNotPaused for queue in BSCGovernor

abi/bscgovernor.abi, abi/stakehub.abi, contracts/BC_fusion/StakeHub.sol, test/StakeHub.t.sol, test/utils/interface/IBSCGovernor.sol, test/utils/interface/IStakeHub.sol
This pr is to update `handleSynPackage` logic of `StakeHub`
* set `handleSynPackage` of `StakeHub` to revert when delegator in blacklist
=> chore: revert transaction when delegator in blacklist

abi/bscvalidatorset.abi, contracts/BC_fusion/StakeHub.sol, test/utils/interface/IBSCValidatorSet.sol
This pr is to fix the issue of no syncing govToken in `_doMigration`
* sync govToken in `_doMigration`
=> fix: sync govToken in `_doMigration`

contracts/Staking.sol
This pr is to address the issue of the contract state not being updated correctly.
* add `isAutoUndelegate` for auto `DistributeUndelegatedSynPackage`
=> fix: add `isAutoUndelegate` for auto `DistributeUndelegatedSynPackage`

abi/bscvalidatorset.abi, contracts/BC_fusion/StakeHub.sol, contracts/BSCValidatorSet.sol, contracts/TokenHub.sol, test/TokenHub.t.sol, test/utils/interface/IBSCValidatorSet.sol
This pr is to forbid the `transferOut` method in `TokenHub` after Feynman upgrade
* deprecate `transferOut` in `TokenHub`
* optimize some annotations and view functions in `BSCValidatorSet`
=> feat: deprecate `transferOut` in `TokenHub`

contracts/BC_fusion/StakeHub.sol
This pr is to add `whenNotPaused` to slash functions in `StakeHub`
* add `whenNotPaused` to slash functions
=> feat: add `whenNotPaused` to slash functions

contracts/BC_fusion/TokenRecoverPortal.sol
#recover function should not be called before the approval address is set.
=> fix: check approval address is not 0x0

contracts/TokenHub.sol
emit NotBoundToken event for off-chain service, to notify user and project team to handle their token recovery.
=> feat: emit NotBoundToken event

abi/bscgovernor.abi, abi/stakehub.abi, contracts/BC_fusion/BSCGovernor.sol, contracts/BC_fusion/StakeHub.sol, contracts/BC_fusion/TokenRecoverPortal.sol, contracts/BC_fusion/extension/Protectable.sol, scripts/generate.py, test/utils/interface/IBSCGovernor.sol, test/utils/interface/IStakeHub.sol
This pr is to refactor the `StakeHub`, `BSCGovernor` and `TokenRecoverPortal` contracts
* add `Protectable` contract
=> chore: refactor codes

contracts/BC_fusion/TokenRecoverPortal.sol, test/TokenRecoverPortal.t.sol, test/utils/Deployer.sol, test/utils/interface/ITokenRecoverPortal.sol
unit-test for TokenRecoverPortal
* add TokenRecoverPortal test files and rebase from bc-fusion
=> test: unit-test for TokenRecoverPortal

contracts/BC_fusion/TokenRecoverPortal.sol, test/TokenRecoverPortal.t.sol
add failed cases to the TokenRecoverPortal unit-test
* add more test cases to TokenRecoverPortal
=> test: add failed cases to TokenRecoverPortal unit-test

abi/bscgovernor.abi, abi/stakehub.abi, contracts/BC_fusion/StakeHub.sol, contracts/BC_fusion/extension/Protectable.sol, contracts/BSCValidatorSet.sol, contracts/SlashIndicator.sol, contracts/Staking.sol, test/TokenRecoverPortal.t.sol, test/utils/interface/IBSCGovernor.sol, test/utils/interface/IStakeHub.sol, test/utils/interface/ITokenRecoverPortal.sol
This pr is to fix some issues from audit reports
=> chore: fix audit issues

contracts/BSCValidatorSet.sol
The current implementation is not easy to understand because `numOfFelony` will increase in two different place.
After change, we count the number of felony validators just before we use it to generate the slice.
=> fix: improve the code readablity

abi/stakehub.abi, contracts/BC_fusion/StakeHub.sol, contracts/BSCValidatorSet.sol, contracts/interface/IStakeHub.sol, test/Governor.t.sol, test/StakeHub.t.sol, test/TokenRecoverPortal.t.sol, test/utils/interface/IStakeHub.sol, test/utils/interface/ITokenRecoverPortal.sol
This pr is to fix an issue that a validator could avoid being slashed by editing consensus address
=> fix: add check in `_forceMaintainingValidatorsExit`

contracts/BC_fusion/BSCGovernor.sol
Since the target address of the text proposal is the proposer address itself, text proposal will not be proposed due to the whitelist targets check in `propose()`
=> feat: remove whitelist check while propose, move the check to queue and execute

contracts/BSCValidatorSet.sol
This PR aims to solve two issue:
1. The function updateValidatorSetV2() will distribute incoming rewards for reach validators, for the best security practice(check-effects-interactions), the incoming reset code should be put ahead of the external function calls.
2. Add the address(0) check in the final function _forceMaintainingValidatorsExit().
=> fix: add empty address check before validator update and clear state before external call

contracts/BC_fusion/StakeHub.sol
This pr is to fix an error within `StakeHub`.
The BNB should be refunded to `TokenHub` if stake migration failed.
* transfer BNB back to `TokenHub` when `_doMigration` failed
=> fix: transfer BNB back to tokenHub when `_doMigration` failed

contracts/BSCValidatorSet.sol
This pr is to fix an issue in `exitMaintenance` method.
* advance the slash operation
=> fix: prevent outOfGas issue

test/Governor.t.sol, test/SlashIndicator.t.sol, test/StakeHub.t.sol, test/TokenRecoverPortal.t.sol, test/ValidatorSet.t.sol, test/utils/Deployer.sol
This pr is to fix errors in unit tests
* remove init call in unit tests after bc-fusion
=> chore: remove init call in unit tests after bc-fusion

contracts/BC_fusion/StakeHub.sol, test/StakeHub.t.sol, test/utils/interface/IStakeHub.sol
add agent address for validators
Agent can execute `editConsensusAddress`, `editCommissionRate`, `editDescription`, `editVoteAddress` for his operator. 
* add agent address for validators
* ...
=> feat: add agent address for validators

abi/bscvalidatorset.abi, contracts/BSCValidatorSet.sol, test/SlashIndicator.t.sol, test/ValidatorSet.t.sol, test/utils/interface/IBSCValidatorSet.sol
feat: define turnLength and systemRewardAntiMEVRatio for BEP-341
two tests will pass by following command
```
cd contracts 
forge test --match-test testDeposit --match-contract ValidatorSetTest
forge test --match-test testGov --match-contract ValidatorSetTest
```
* ...
=> feat: define turnLength and systemRewardAntiMEVRatio for BEP-341

contracts/BC_fusion/StakeHub.sol
it should not change `agentToOperator` while `newAgent` is zero address in `updateAgent` function
before this fix:
validator A set agent1 
agentToOperator[address(0)] == address(0)
validator A update agent to address(0)   => caused agentToOperator[address(0)] == validator A
after fix:
validator A set agent1 
agentToOperator[address(0)] == address(0)
validator A update agent to address(0)   => agentToOperator[address(0)] == address(0)
* not change `agentToOperator` while `newAgent` is zero address in `updateAgent` function
* ...
=> fix: should not change agentToOperator while newAgent is zero address

.github/workflows/check-genesis.yml, scripts/check-genesis-bytecode.ts
add script and ci to check if genesis is generated from latest contracts
make sure `genesis.json` is generated from current contracts
* add check-genesis-bytecode.ts script to compare bytecode from current and generated file
* add check-genesis.yml ci job
=> feat: add script and ci to check if genesis is generated from latest contracts 

scripts/flatten.sh
These 6 contracts were deprecated after BC-Fusion:
```
contracts/deprecated/CrossChain.sol
contracts/deprecated/RelayerHub.sol
contracts/deprecated/RelayerIncentivize.sol
contracts/deprecated/Staking.sol
contracts/deprecated/TendermintLightClient.sol
contracts/deprecated/TokenManager.sol
```
* ...
=> fix: update the flatten.sh script

.github/workflows/unit-test.yml, test/Governor.t.sol, test/SlashIndicator.t.sol, test/ValidatorSet.t.sol
fix: fix unit test
1. BSC mainnet has passed the `Maxwell` hardfork, resulting in changes to certain parameters. The test cases have been updated accordingly.
2. The latest Foundry version has a contract creation bug, so we downgrade Foundry to v1.2.1.
3. Replaced `console.log` with `console2.log` to support the `uint256` type.
* ...
=> fix: fix unit test
